#!/bin/sh
APPDIR=../..;
if [ "$GWT_HOME" == "" ]; then
	echo "The environment variable GWT_HOME is not defined, it should point to a valid GWT installation."
	exit
fi

java -Xmx128m -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev.jar:$GWT_HOME/gwt-dev-mac.jar:../../../../@JARNAME@" com.google.gwt.dev.HostedMode -war "$APPDIR/war" "$@" -startupUrl @INDEX_HTML@ @ENTRY_MODULE@
