#!/bin/sh
APPDIR=../..;
if [ "$GWT_HOME" == "" ]; then
	echo "The environment variable GWT_HOME is not defined, it should point to a valid GWT installation."
	exit
fi

java -Xmx128M -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar:../../../../gwt-mobile-webkit-iui.jar" com.google.gwt.dev.Compiler -war "$APPDIR/war" "$@" com.google.code.gwt.iui.sample.helloiui.HelloiUI
