#!/bin/sh
APPDIR=../..;
if [ "$GWT_HOME" == "" ]; then
	echo "The environment variable GWT_HOME is not defined, it should point to a valid GWT installation."
	exit
fi

java -Xmx128M -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-mac.jar:../../../../gwt-mobile-webkit-appcache.jar" com.google.gwt.dev.Compiler -war "$APPDIR/war" -startupUrl HelloApplicationCache.html "$@" com.google.code.gwt.appcache.sample.helloappcache.HelloApplicationCache;
