#!/bin/sh
APPDIR=../..;
if [ "$GWT_HOME" == "" ]; then
	echo "The environment variable GWT_HOME is not defined, it should point to a valid GWT installation."
	exit
fi

java -Xmx128m -XstartOnFirstThread -d32 -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-mac.jar:../../../../gwt-mobile-webkit-iui.jar" com.google.gwt.dev.HostedMode -war "$APPDIR/war" "$@" -startupURL HelloiUI.html com.google.code.gwt.iui.sample.helloiui.HelloiUI
